title: GHLearningLab
description: >-
  631-GHLearningLab template course from github's learning lab for those
  interested, particularly the ssrucs students enrolling in the courses taught
  by PhanuLAB staffs from the first semester of 2020 academic year beginning
  from July 10, 2020 onward.
template:
  repo: ghlearninglab-template
  name: ghlearninglab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
