title: GH Learning Lab Template Course for SSRU CSLabs
description: >-
  641-GHLearningLab template course from GitHub's learning lab for ssrucs
  students enrolling in the courses taught by PhanuLAB staffs from the first
  semester of 2021 academic year beginning from July 12, 2021 onward and for
  those interested in..
template:
  repo: ghlearninglab-ssrucslab
  name: ssrucslab
  description: ssrucs computer labs
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
